spring.application.name=StudyHelper

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/studyhelper}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:studyhelper}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:studyhelper}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

file.upload.dir=${FILE_UPLOAD_DIR:/app/uploads}

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
